#include "GenmapParams.h"

const PilDescription GammaExtractParams[] = {
	{ PilString, "outfile", "Output file name" },
	{ PilString, "logfile", "Grid log index file name" },
	{ PilString, "evtfile", "Event file index file name" },
	{ PilString, "sarFileName", "Effective area file name" },
	{ PilString, "edpFileName", "Energy dispersion file name" },
	{ PilString, "timelist", "Time intervals file name" },
	{ PilReal, "mres", "Bin size (degrees)" },
	{ PilReal, "la", "Longitude of map center (galactic)" },
	{ PilReal, "ba", "Latitude of map center (galactic)" },
	{ PilReal, "lonpole", "Rotation of map (degrees)" },
	{ PilReal, "albrad", "Radius of earth albedo (degrees)" },
	{ PilReal, "y_tol", "Boresight movement tolerance (degrees)" },
	{ PilReal, "roll_tol", "Roll tolerance (degrees)" },
	{ PilReal, "earth_tol", "Earth tolerance (degrees)" },
	{ PilInt, "phasecode", "Orbital phase code" },
	{ PilInt, "timestep", "LOG file step size" },
	{ PilReal, "index", "Spectral index" },
	{ PilReal, "tmin", "Initial time (sec)" },
	{ PilReal, "tmax", "Final time (sec)" },
	{ PilReal, "emin", "Minimum energy" },
	{ PilReal, "emax", "Maximum energy" },
	{ PilReal, "fovradmin", "Min radius of field of view (degrees)" },
	{ PilReal, "fovradmax", "Max radius of field of view (degrees)" },
	{ PilInt, "filtercode", "Event filter code" },
	{ PilReal, "timeslot", "Time slot" },
	{ PilNone, "", "" }
};
